#pragma once

#define PORT_TCP_DEFAULT 4242
#define PORT_UDP_DEFAULT 4243
#define MAX_CLIENTS 2

#define LOGIN_RESP 0x02
#define TCP_REQUEST_FLAG 0x01
#define REQUEST_SUCCESS 0x01
#define REQUEST_ERROR 0x00
#define HEADER_SIZE 6
